### PR TITLE
Playbook and set of tasks for managing VM mounts.

### PR DESCRIPTION
**Pull request by wtcross**
This change introduces a new playbook and task
file that it includes in order to manage each mount
of a new VM being provisioned.

### CODE REVIEW

**Comment by wtcross** [comment]
@bhirsch70 I haven't tested this playbook, but I think that it'll do roughly what we want for this use case.

**Comment by wtcross** [comment]
I'm mostly not sure whether or not it's necessary to store and reuse the original mount point in [`operations/fix-device.yml`](https://github.com/wtcross/Ansible-LVM/blob/9d6942b1891cd764c91dfa1052a9881121df8d98/operations/fix-device.yml).

**Comment by wtcross** [comment]
Note that when running this it's necessary to do something like the following:
`ansible-playbook lvm-operations.yml -u vra_user --ask-pass --ask-sudo-pass`

The user and credentails _should_ be used in the second play when targeting all the VMs. Haven't tested it yet, so not sure. 😃

**Comment by bhirsch70** [comment]
wow, that was fast.  Thanks Tyler.  I'll test the changes

**Comment by bhirsch70** [comment]
Can you give more detail of how inventory is being handled?  Not sure how
to test this.

Bill Hirsch, Solution Architect
State, Local, and Education
724.719.7106
Red Hat, Inc. | TRIED. TESTED. TRUSTED
Find out why at Trusted | Red Hat <https://www.redhat.com/en/about/trusted>

**Pull request merged**
